version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=fastapi
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  tasks:
    build: ./tasks
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - ./tasks:/app
    ports:
      - 8001:8080
    
  users:
    build: ./users
    depends_on:
      - tasks
    env_file:
      - ./.env
    volumes:
      - ./users:/app
    ports:
      - 8002:8080

  auth:
    build: ./auth
    depends_on:
      - tasks
    env_file:
      - ./.env
    volumes:
      - ./auth:/app
