apiVersion: v1

kind: Service

metadata:
  name: auth-service

spec:
  selector:
    app: auth-api
  tyee: ClusterIP
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80

---

apiVersion: apps/v1

kind: Deployment

metadata:
  name: auth-deployment

spec:
  selector:
    matchLabels:
      app: auth-api
  containers:
    - name: auth-api
      image: ''

